name: CI
on:
  workflow_run:
    workflows: ['pre-release', 'Pre-release', 'pre-release.yml']
    types:
      - completed

jobs:
  quality-assurance:
    uses: ./.github/workflows/quality-assurance.yml
