name: Quality-assurance
on:
  workflow_call:

jobs:
  quality-assurance:
    name: quality-assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Cache modules
        id: cache-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-modules
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Create build cache key files glob env variable
        run: |
          echo "build-cache-files=\
            'examples/**/*.[jt]s', \
            'examples/**/*.[jt]sx', \
            'examples/**/*.[jt]s', \
            'examples/**/*.[jt]sx', \
            'libs/**/*.[jt]s', \
            'libs/**/*.[jt]sx', \
            'libs/**/*.[jt]s', \
            'libs/**/*.[jt]sx', \
            'e2e/**/*.[jt]s', \
            'e2e/**/*.[jt]sx', \
            'e2e/**/*.[jt]s', \
            'e2e/**/*.[jt]sx' \
          " >> $GITHUB_ENV
      - name: Cache build
        uses: actions/cache@v2
        env:
          cache-name: build-cache
        with:
          path: |
            ./node_modules/.cache
            ./examples/next/.next/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles(env.build-cache-files) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - run: yarn --frozen-lockfile

      - run: yarn nx workspace-lint
      - run: yarn nx format:check
      - run: yarn nx affected:lint --parallel=3
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_DEFAULT_TOKEN }}
      - run: yarn nx affected:test --parallel=3 --ci --code-coverage
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_DEFAULT_TOKEN }}
      - run: yarn nx affected --parallel=3 --target=testTypes
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_DEFAULT_TOKEN }}
      - run: yarn nx affected:build --parallel=3
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_DEFAULT_TOKEN }}
      - run: yarn nx affected:e2e --parallel=2 --skip-nx-cache
        id: e2eTests
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_DEFAULT_TOKEN }}
      - name: Upload e2e result artifact
        if: ${{ failure() && steps.e2eTests.conclusion == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-reports
          path: dist/cypress/
          retention-days: 2
          if-no-files-found: error
